import './globals.css';

import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import type { Metadata } from 'next';
import { Mulish } from 'next/font/google';

const mulish = Mulish({
  subsets: ['latin-ext'],
  variable: '--font-mulish',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.className} dark antialiased`}>
        <ClerkProvider
          appearance={{
            baseTheme: dark,
          }} // Define o tema escuro para o UserButton do Clerk
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
